repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: debug-statements
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: no-commit-to-branch

- repo: local
  hooks:
    - id: pipenv-check
      name: Pipenv Check
      entry: pipenv check
      language: system
      files: Pipfile
      verbose: false
      pass_filenames: false

    - id: check-datetime-now
      name: check_datetime_now
      description: Prefer datetime.utcnow()
      language: pygrep
      entry: 'datetime\.now\(\)'
      types: [python]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
      args: ['--exclude=docs/*,*migrations*', '--ignore=E501,W503,E203']

- repo: https://github.com/timothycrosley/isort
  rev: 5.5.2
  hooks:
    - id: isort
      args: ['--check-only', '--diff']

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
    - id: python-check-mock-methods

- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black

- repo: git@github.com:olist/hulks.git
  rev: 0.4.1
  hooks:
    - id: check-filename
    - id: check-invalid-domains
    - id: check-logger
    - id: check-default-commentary-django-migration
    - id: check-django-migrations-filename
    - id: check-mutable-defaults
