[tool.black]
line-length = 99
target-version = ["py37"]

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_localfolder = "apps,utils,tests,jsonbox_api"
sections = "FUTURE,STDLIB,THIRDPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
